# Form implementation generated from reading ui file 'PollVoteGUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(400, 395)
        self.comboBox = QtWidgets.QComboBox(parent=MainPage)
        self.comboBox.setGeometry(QtCore.QRect(180, 70, 181, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=MainPage)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 110, 181, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=MainPage)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 160, 181, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.radioButton = QtWidgets.QRadioButton(parent=MainPage)
        self.radioButton.setGeometry(QtCore.QRect(70, 250, 101, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=MainPage)
        self.radioButton_2.setGeometry(QtCore.QRect(70, 290, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=MainPage)
        self.radioButton_3.setGeometry(QtCore.QRect(230, 250, 91, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=MainPage)
        self.radioButton_4.setGeometry(QtCore.QRect(230, 290, 82, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.label = QtWidgets.QLabel(parent=MainPage)
        self.label.setGeometry(QtCore.QRect(150, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=MainPage)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=MainPage)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=MainPage)
        self.label_4.setGeometry(QtCore.QRect(40, 150, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=MainPage)
        self.label_5.setGeometry(QtCore.QRect(140, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(parent=MainPage)
        self.pushButton.setGeometry(QtCore.QRect(310, 360, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=MainPage)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 330, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(MainPage)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "Form"))
        self.comboBox.setItemText(0, _translate("MainPage", "Select County"))
        self.comboBox.setItemText(1, _translate("MainPage", "Douglas"))
        self.comboBox.setItemText(2, _translate("MainPage", "Sarpy"))
        self.comboBox.setItemText(3, _translate("MainPage", "Cass"))
        self.comboBox.setItemText(4, _translate("MainPage", "Saunders"))
        self.radioButton.setText(_translate("MainPage", "Arthur Morgan"))
        self.radioButton_2.setText(_translate("MainPage", "The Doctor"))
        self.radioButton_3.setText(_translate("MainPage", "The Courier"))
        self.radioButton_4.setText(_translate("MainPage", "Tarnished"))
        self.label.setText(_translate("MainPage", "PollVote"))
        self.label_2.setText(_translate("MainPage", "County"))
        self.label_3.setText(_translate("MainPage", "Name [First, Last]"))
        self.label_4.setText(_translate("MainPage", "ID"))
        self.label_5.setText(_translate("MainPage", "Candidates"))
        self.pushButton.setText(_translate("MainPage", "Admin Mode"))
        self.pushButton_2.setText(_translate("MainPage", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainPage = QtWidgets.QWidget()
    ui = Ui_MainPage()
    ui.setupUi(MainPage)
    MainPage.show()
    sys.exit(app.exec())
